### ISSUE TITLE
Transfer project to sugarlabs

### ISSUE THREAD

**Issue by davelab6** [agu-z/chart#2]
Please check out https://wiki.sugarlabs.org/go/Infrastructure_Team/Migrating_to_GitHub and transfer this repo to https://github.com/sugarlabs :)

**Comment by quozl** [comment]
Forked.

**Comment by agu-z** [comment]
@davelab6 @quozl I'm sorry I'm seeing this years later. I've noticed your fork is some commits ahead but let me know if you're still interested in this. I promise to get it done before 2030 🙃

**Comment by quozl** [comment]
I'm fine with you leaving the project in your GitHub personal account.  There are good reasons why a developer would want to do that.

If you wish, you can give me commit rights to your repository and I'll maintain your master branch when I'm maintaining the Sugar Labs master branch.

**Comment by agu-z** [comment]
I understand that but in reality I just started this project, you folks are the ones keeping it alive and I really appreciate that! 
I gave you push access. Let me know if you want to transfer it, I’d be happy to do so if you want :)

**Comment by quozl** [comment]
Thanks!
